version: 0.2

env:
  variables:
    TEMPLATE: "ansible_cf_demo.json"
    BUCKET_PATH: "gaystafford_cloud_formation/cf_demo/"
phases:
  install:
    runtime-versions:
      python: 3.7
      commands:
       - command
       - command
  pre_build:
    commands:
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint -t $TEMPLATE
      - aws cloudformation validate-template --template-body file://$TEMPLATE
  post_build:
    commands:
      - aws s3 cp $TEMPLATE s3://$BUCKET_PATH