version: 0.2

env:
  parameter-store:
    BUCKET_PATH: "/anisble_demo/template_bucket"

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt -q
      - cfn-lint -v
  build:
    commands:
      - sh buildspec_files/build.sh
  post_build:
    commands:
      - aws s3 ls s3://$BUCKET_PATH

artifacts:
  files:
    - '**/*'
  base-directory: 'cfn_templates'
  discard-paths: yes